{
 "title": "DN42",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "<h1> Infos </h1>\nASN: AS4242420663 <br>\nAS-NAME: AS-CYBERTRASH-DN42 <br>\nIPv6: fd49:d69f:6::/48 <br>\nIPv4: 172.22.179.128/27 <br>\nNOC Contact: noc@ketamin.trade <br>\nPeering requests are welcome <br>\nLooking Glass (if it isnt broken):<a href=\"https://lg.ketamin.trade/\"> lg.ketamin.trade </a>\n"
   }
  },
  {
   "title": "DN42 Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"nodes\", device=~\".*(dn42|kioubit).*\"}[$__rate_interval]) * 8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"nodes\", device=~\".*(dn42|kioubit).*\"}[$__rate_interval]) * 8",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "Bird Prefix Import Count IPv4",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "expr": "bird_protocol_prefix_import_count{ip_version=\"4\",proto=\"BGP\"}",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "legendFormat": "{{name}}",
     "query": "SELECT\n    $timeSeries as t,\n    count()\nFROM $table\nWHERE $timeFilter\nGROUP BY t\nORDER BY t",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Bird Prefix export Count IPv4",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "expr": "bird_protocol_prefix_export_count{ip_version=\"4\",proto=\"BGP\"}",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "legendFormat": "{{name}}",
     "query": "SELECT\n    $timeSeries as t,\n    count()\nFROM $table\nWHERE $timeFilter\nGROUP BY t\nORDER BY t",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Bird Prefix Import Count IPv6",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "expr": "bird_protocol_prefix_import_count{ip_version=\"6\",proto=\"BGP\"}",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "legendFormat": "{{name}}",
     "query": "SELECT\n    $timeSeries as t,\n    count()\nFROM $table\nWHERE $timeFilter\nGROUP BY t\nORDER BY t",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Bird Prefix Import Count IPv6",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "expr": "bird_protocol_prefix_export_count{ip_version=\"6\",proto=\"BGP\"}",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "legendFormat": "{{name}}",
     "query": "SELECT\n    $timeSeries as t,\n    count()\nFROM $table\nWHERE $timeFilter\nGROUP BY t\nORDER BY t",
     "round": "0s"
    }
   ]
  }
 ]
}